#!/usr/bin/env bash

mkdir -pv $LFS/{etc,var} $LFS/usr/{bin,lib,sbin}

pushd $LFS
for i in bin lib sbin; do
  ln -sv usr/$i $LFS/$i
done
popd

case $(uname -m) in
  x86_64) mkdir -pv $LFS/lib64 ;;
esac

mkdir -pv $LFS/tools
